[metadata]
name = myce_student_onboarding
version = 0.1
description = Per-term student onboarding checklist for MyCE
long_description = file: README.md
url = https://www.canusia.com/
author = Avinash Kadaji
author_email = avi@canusia.com
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find:
python_requires = >=3.8
install_requires =
    Django >= 4.2
