# Generated by Django 5.2.13 on 2026-04-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cis', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('total_steps', models.PositiveSmallIntegerField(default=0)),
                ('completed_steps', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='cis.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('url_name', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='student_onboarding.studentonboarding')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='studentonboarding',
            index=models.Index(fields=['student', 'term'], name='student_onb_student_99a0ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentonboarding',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentonboardingstep',
            unique_together={('onboarding', 'key')},
        ),
    ]
