# Generated by Django 5.2.13 on 2026-04-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '__first__'),
        ('student_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonboarding',
            name='last_notified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyOnboardingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('step_key', models.CharField(blank=True, default='', max_length=64)),
                ('total_onboardings', models.PositiveIntegerField(default=0)),
                ('started_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('step_completed_count', models.PositiveIntegerField(default=0)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'term'], name='student_onb_date_7c7f8b_idx'), models.Index(fields=['term', 'highschool'], name='student_onb_term_id_a824e2_idx')],
                'unique_together': {('date', 'term', 'highschool', 'step_key')},
            },
        ),
    ]
